# enable search
enableSearch = true

# socials
twitter = "@janedoe"
largeTwitterCard = false # set to true if you want to show a large twitter card image. The default is a small twitter card image

#introDescription = "Pet Parent, technologist, perpetual student, teacher, continual incremental improvement proponent."
# introURL = "about/" # set the url for the 'read more' button below the introDescription, or set to false to not show the button
# description = "A theme based on VMware's Clarity Design System for publishing technical blogs with Hugo." # Set your site's meta tag (SEO) description here. Alternatively set this description in your home page content file e.g. content/_index.md. Whatever is set in the latter will take precedence.
# keywords = ["design", "clarity", "hugo theme"] # Set your site's meta tag (SEO) keywords here. Alternatively set these in your home page content file e.g. content/_index.md. Whatever is set in the latter will take precedence.

# showShare = false # Uncomment to not show share buttons on each post. Also available in each post's front matter.

# Google analytics Id
ga_analytics = "G-E157N1JNPM"

# limit the number of taxonomies links shown on the sidebar of each page by default.
numberOfTagsShown = 14 # Applies for all other default & custom taxonomies. e.g categories, brands see https://gohugo.io/content-management/taxonomies#what-is-a-taxonomy

# Whether to default to storing images and other assets in the `static` directory, or use Hugo page bundles.
# Switch to `true` if you'd like to group assets with the post itself (as a "leaf bundle").
# This can be overridden at the page level; what is set below acts as the default if no page variable is set.
# Details on page bundles: https://gohugo.io/content-management/page-bundles/#leaf-bundles
usePageBundles = false

# Path variables
#
# By default, each of these directories are children of the `static` directory.
#
# In some Apache server installs, these directory names could conflict and you
# may want to change them. See:
# https://github.com/chipzoller/hugo-clarity/issues/74
#
# If you change the names of these directories, be sure to copy the contents of
# the originals to get the files included with Hugo Clarity.
#
# Images:
imagesDir = "images/" # without a leading forward slash
# Icons:
iconsDir = "icons/" # without a leading forward slash
# Fonts:
fontsDir = "fonts/" # without a leading forward slash

# Social media sharing image: Will be used on Twitter, Facebook, LinkedIn, etc.
# when a given page has no other image present.
fallBackOgImage = "images/thumbnail.png"

# Logo image
logo = "logos/logo.png"

# center logo on navbar
centerLogo = false # Set to "true" for centering or "false" for left aligned.

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 7

# disable showing line numbers by default. Switch to `true` if you'd rather have them on.
codeLineNumbers = false

# enable math notation. Switch to `true` to enable mathjax in your site.
enableMathNotation = false

# directory(s) where your articles are located
mainSections = ['posts', 'courses'] # see config details here https://gohugo.io/functions/where/#mainsections

# Label Non inline images on an article body
figurePositionShow = false # toggle on or off globally
# you can toggle this behaviour on or off on per page using the same variable inside your articles frontmatter
figurePositionLabel = "Figure" # the text before image number e.g Figure 1.0

# Set the collapsed mobile navigation to either appear from the left or the right
mobileNavigation = "left" # if you prefer right change to 'right'

# some site owners want to decide how they would like their sites to be introduced users. These settings give you as a site owner to decide how the user will view your site for the first time.

# please note that you cannot enforce both modes at the same time. i.e by enforcing one mode, you priotise it over the other (by setting it to true). enforceDarkMode will be commented out

# please also not that mode toggle UI will remain in place. That way, if a user prefers darkmode, they can have their way.

#enforceLightMode = false
 enforceDarkMode = true

# customize footer icon. see issue https://github.com/chipzoller/hugo-clarity/issues/77
# footerLogo = "icons/copy.svg"

 #Customize Sidebar Disclaimer Text
 sidebardisclaimer = true
 disclaimerText = "The opinions expressed on this site are my own personal opinions and do not represent my employer’s view in any way."

# Text for the languages menu.
languageMenuName = "🌐"

# Title separator, default to |.
# titleSeparator = "|"

# Enable or disable comments globally. Default to true.
# comments = false

# Enable or disable Utterances (https://github.com/utterance/utterances) Github Issue-Based Commenting
# utterances = true  #Run the utterances script in the single.html layout to load https://utteranc.es comments
# utterancesRepo = "GHUsername/Repository.Name" # Utterances is enabled when this param is set
# utterancesTheme = "github-light" # Default: github-dark
# utterancesIssueTerm = "pathname" # Default: pathname

# Maximum number of recent posts. (default: 8)
# numberOfRecentPosts = 8

# Maximum number of featured posts. (default: 8)
# numberOfFeaturedPosts = 8

# Pin featured posts in list.
# pinFeatured = true

# Maximum number of pinned featured posts. (default: 8)
# numberOfPinnedPosts = 8

# Date format. Checkout https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for details.
# dateFormat = "2006-01-02" # Default to "Jan 2, 2006".
# customFonts = false # toggle to true if you want to use custom fonts only.

# The year when ths website was created, this value is used in the copyright
# notice of the footer.
# since = 2016

# Show related content at the end of an article based on the 'series' taxonomy. Can be set in post front matter.
showRelatedInArticle = true
showRelatedInSidebar = false

# website author
[author]
name = "Mandar Dharmadhikari"
photo = "images/profilepic.png" #include this if you would like to show the author photo on the sidebar

[plausible_analytics]
enable = false # to enable plausible analytics set to true.
websiteDomain = "example.com" # domain name of your website, most cases same as your base url
# plausibleDomain = "plausible.io" # default is set to plausible.io, only required if plausible is selfhosted
# scritpName = "plausible" # default is set to plausible, only required if using a custome name for script

[matomo_analytics]
enable = false # To enable matomo analytics change to `true`.
websiteDomain = "example.com" # Set the domain name of your website, in most cases same as your base URL this is required.
matomoDomain = "matomo.example.com" # Set to Matomo domain
matomoSiteID = "1" # Default is set to 1, change this to the siteid being tracked

#Giscus integration
[comments.giscus]
repo = "codidharma/commentsrepo" # Repo where the comments will live
repo_id = "R_kgDOIAABcg" # Repo where the comments will live
category = "Announcements" # Repo where the comments will live
category_id = "DIC_kwDOIAABcs4CRcfN" # Repo where the comments will live
mapping = "pathname" # How Utterances will match comment to page
strict = 1
reactions_enabled = 0
metadata = 0
input_position= "top"
theme = "preferred_color_scheme"
label = "comment" # Label applied to issue by utteranc.es bot
lang = "en"

# Custom CDN Javascript embeddings
[[cdnJS.items]]
  url="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"


[about]
bannerLocation = "images/about/banner.jpg"

[talks]
bannerLocation = "images/talks/banner.jpg"

[profile.intro]
  intro = "Hi, my name is"
  title = "Mandar"
  subtitle = "I design and build code that solves business problems"
  content = """Experienced pro-code and low-code cloud solutions architect with more than a decade of expertise in building line of business services and systems integration across insurance
   and banking verticals."""
  image = "/images/mandar.jpg"

[profile.intro.resume]
    url="https://example.com"
    download = true

[[profile.intro.clickableActions]]
  url= "https://twitter.com/codidharma"
  actionName = "Twitter"
  ionIconName = "logo-twitter"

[[profile.intro.clickableActions]]
  url="https://www.linkedin.com/in/mandar-dharmadhikari"
  actionName = "linkedin"
  ionIconName = "logo-linkedin"

[[profile.intro.clickableActions]]
  url="https://www.linkedin.com/in/mandar-dharmadhikari"
  actionName = "GITHUB "
  ionIconName = "logo-github"


[profile.aboutme]
  enable = true
  title = "More About Me"
  image = "/images/mandar.jpg"
  content = """
Technology Nerd with a penchant for public speaking. I enjoy marrying the business needs with appropriate technologies to deliver business value.
I also enjoy mentoring colleagues and have managed small and medium size teams
"""

 [profile.aboutme.skills]
    enable = true
    title = "I am experienced in:"
    items = [ "Cloud Native Systems Design","Test Driven Development", "CRM Systems Design", "Agile Development","Team Management", "Public Speaking" ]

[profile.experience]
  enable = true
  title= "My work Experience"
  index = false

  [[profile.experience.items]]
    job = "Business Architecture Manager"
    company = "Accenture India"
    companyUrl = "https://www.accenture.com/"
    date = "Jan 2021 - Present"
    location = "Pune, India"
    content = """
  - Work as a cloud solution architect who focuses on building scalable serverless applications for Insurance and Banking verticals.
  - Responsible for designing insurance specific CRM and Low code Systems.
  - My tech stack mainly involves C#, .Net Core, Azure and Power Platform.
  - Responsible for management of two two pizza teams and report to senior Accenture leadership in India."""

  [[profile.experience.items]]
    job = "Technical Consultant"
    company = "Chamonix IT Solutions"
    companyUrl = "https://chamonix.com.au/"
    date = "Dec 2019 - Dec 2020"
    location = "Adelaide, Australia"
    content = """
  - Worked as a consultant. This was an individual contributor role.
  - Was responsibility of designing and building cloud applications and advising government and private sector clients on adoption of cloud technologies.
  - Used C#, Microsoft Azure, WSO2(integration analysis only) for daily work"""

  [[profile.experience.items]]
    job = "Delivery Module Lead"
    company = "Mphasis Australia Pty Ltd "
    companyUrl = "https://www.mphasis.com/"
    date = "Nov 2016 - Nov 2019"
    location = "Adelaide, Australia"
    content = """
  - Worked as a senior software engineer in a client facing role in banking vertical.
  - Was responsible for building Enterprise Level Systems Integrations using Microsoft BizTalk server.
  - In later stages, was responsible for designing integrations systems which communicated with modern and legacy systems.
  - Tech stack of choice was Microsoft BizTalk Server and C#."""


[[profile.experience.items]]
    job = "Software Developer"
    company = "Syntel-Atos"
    companyUrl = "https://atos.net/"
    date = "May 2016 - Nov 2016"
    location = "Pune, India"
    content = """
  - Worked as a Integration System Administrator in healthcare vertical.
  - Was responsible for maintenance of the client BizTalk server systems.
  - Typically used Microsoft BizTalk Server and PowerShell for my daily tasks. """

[[profile.experience.items]]
    job = "Junior Software Developer"
    company = "Tata Consultancy Services"
    companyUrl = "https://www.tcs.com/"
    date = "Dec 2012 - May 2016"
    location = "Mumbai, India"
    content = """
- Worked as a junior developer for a insurance client.
- Was responsible for building and maintaining systems integrations.
- Used Microsoft BizTalk Server and PowerShell for daily tasks."""


[profile.education]
  enable = true
  index = false
  title="My Education"

[[profile.education.items]]
    title = "Bachelor of Engineering in Electronics and Telecommunication"
    class = "Class of 2012"
    date = "2009 - 2013"
    GPA = "3.7 out of 5.0"
    content = ""
  [profile.education.items.school]
      name = "Sant Gadge Baba Amravati University"


[profile.techstack]
  enable = true

    [[profile.techstack.items]]
    title = "C Sharp"
    image="/images/tech/cshp.svg"
    content = "I solved all problems with optimal solution."


    [[profile.techstack.items]]
    title = "Python"
    image="/images/tech/python.svg"
    content = "Developed a product using Artificial Intelligence."

    [[profile.techstack.items]]
    title = "Hugo Scripting"
    image="/images/tech/hugo.svg"
    content = "Developed a theme and getting 1K+ downloads per month."


    [[profile.techstack.items]]
    title = ".NET Core Platform"
    image="/images/tech/netcore.svg"

    [[profile.techstack.items]]
    title = "Microsoft Azure"
    image="/images/tech/azure.svg"

    [[profile.techstack.items]]
    title = "Microsoft Power Platform"
    image="/images/tech/pp.svg"

[profile.certifications]
  enable = true

  [[profile.certifications.items]]
    verificationUrl= "https://www.credly.com/badges/2ed17beb-51ef-4149-9017-6f508a87c491/public_url"
    image="images/certs/ppsa.png"

  [[profile.certifications.items]]
    verificationUrl="https://www.credly.com/badges/9ceb4d15-8b10-4373-932d-155e67db167e/public_url"
    image="images/certs/ppfunc.png"

  [[profile.certifications.items]]
    verificationUrl="https://www.credly.com/badges/466acbbe-b699-4996-8038-e97854d9b00c/public_url"
    image="images/certs/aiengg.png"

  [[profile.certifications.items]]
    verificationUrl="https://www.credly.com/badges/af3e7b58-5263-47e0-b2e1-5433ceb643ab/public_url"
    image="images/certs/salesfunc.png"

    [[profile.certifications.items]]
    verificationUrl="https://www.credly.com/badges/58aa78c3-6713-4c29-9f75-0b214ce15c4b/public_url"
    image="images/certs/ppfund.png"

  [profile.certifications.verify]
  baseURL = "https://www.credly.com/badges"
  actionName = "Verify Badge"
  ionIconName = "shield-checkmark-outline"

  [profile.publicspeaking]
  enable = true
  title = "Public Speaking Activities"
  talksPageUrl = "/talks"
  actionName = "Explore My Talks"
  ionIconName = "arrow-forward-outline"
  content = "I have a zeal for sharing my knowledge"
  banner = "images/talks/banner.jpg"

  [profile.recentPosts]
  enable = true
  folder="posts"
  maxCountToShow = 3
  title = "Recent Posts"
  action="Read More"
  ionIconName = "arrow-forward-outline"
  exploreMoreAction = "Explore Other Posts"
  postUrl= "posts"




